### PR TITLE
Restart worker

### LINKED ISSUE #24: restart background worker on crash

### PR DESCRIPTION
**Pull request by steve-chavez**
Fixes #24.

Also added a safeguard against doing requests against other valid protocols(like ftp, smtp, etc).

### CODE REVIEW

File: src/worker.c [hunk 1]
```diff
@@ -440,7 +442,7 @@ _PG_init(void)
 	snprintf(worker.bgw_library_name, BGW_MAXLEN, "pg_net");
 	snprintf(worker.bgw_function_name, BGW_MAXLEN, "worker_main");
 	snprintf(worker.bgw_name, BGW_MAXLEN, "pg_net worker");
-	worker.bgw_restart_time = BGW_NEVER_RESTART;
+	worker.bgw_restart_time = 32;
```
Comment (steve-chavez) [inline src/worker.c:445]: 32 seconds LGTM. In case the worker crashes, we don't want to fill the logs.

**Comment by steve-chavez** [comment]
I'll merge since the change is simple enough. Also making the tests green.
